using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using CSSPEnums;
using System.Net;

namespace CSSPEnumsGenerateCodeHelper
{
    public partial class EnumsGenerateCodeHelper
    {
        public void EnumsAndPolSourceInfoEnumsWithHelpGenerate()
        {
            Enums enumsEn = new Enums(LanguageEnum.en);
            Enums enumsFr = new Enums(LanguageEnum.fr);

            StringBuilder sb = new StringBuilder();
            StringBuilder sbPol = new StringBuilder();

            FileInfo fiCSSPEnumsDLL = new FileInfo(@"C:\CSSP Code\CSSPEnums\CSSPEnums\bin\Debug\CSSPEnums.dll");
            FileInfo fi = new FileInfo(@"C:\CSSP Code\CSSPEnums\CSSPEnums\EnumsWithHelp.cs");
            FileInfo fiPol = new FileInfo(@"C:\CSSP Code\CSSPEnums\CSSPEnums\PolSourceObsInfoEnumGeneratedWithHelp.cs");
            FileInfo fiCSSPModelsDLL = new FileInfo(@"C:\CSSP Code\CSSPModels\CSSPModels\bin\Debug\CSSPModels.dll");
            FileInfo fiCSSPServicesDLL = new FileInfo(@"C:\CSSP Code\CSSPServices\CSSPServices\bin\Debug\CSSPServices.dll");

            if (!fiCSSPEnumsDLL.Exists)
            {
                ErrorEvent(new ErrorEventArgs("File does not exist [" + fiCSSPEnumsDLL.FullName + "]"));
                return;
            }

            StatusPermanentEvent(new StatusEventArgs("Reading [" + fiCSSPEnumsDLL.FullName + "] ..."));
            List<DLLTypeInfo> DLLTypeInfoCSSPEnumsList = new List<DLLTypeInfo>();
            if (FillDLLTypeInfoList(fiCSSPEnumsDLL, DLLTypeInfoCSSPEnumsList))
            {
                ErrorEvent(new ErrorEventArgs("Could not read the file [" + fiCSSPEnumsDLL.FullName + "]"));
                return;
            }
            StatusPermanentEvent(new StatusEventArgs("Loaded [" + fiCSSPEnumsDLL.FullName + "] ..."));

            if (!fiCSSPModelsDLL.Exists)
            {
                ErrorEvent(new ErrorEventArgs("File does not exist [" + fiCSSPModelsDLL.FullName + "]"));
                return;
            }
            StatusPermanentEvent(new StatusEventArgs("Reading [" + fiCSSPModelsDLL.FullName + "] ..."));
            List<DLLTypeInfo> DLLTypeInfoCSSPModelsList = new List<DLLTypeInfo>();
            if (FillDLLTypeInfoList(fiCSSPModelsDLL, DLLTypeInfoCSSPModelsList))
            {
                ErrorEvent(new ErrorEventArgs("Could not read the file [" + fiCSSPModelsDLL.FullName + "]"));
                return;
            }
            StatusPermanentEvent(new StatusEventArgs("Loaded [" + fiCSSPModelsDLL.FullName + "] ..."));

            if (!fiCSSPServicesDLL.Exists)
            {
                ErrorEvent(new ErrorEventArgs("File does not exist [" + fiCSSPServicesDLL.FullName + "]"));
                return;
            }
            StatusPermanentEvent(new StatusEventArgs("Reading [" + fiCSSPServicesDLL.FullName + "] ..."));
            List<DLLTypeInfo> DLLTypeInfoCSSPServicesList = new List<DLLTypeInfo>();
            if (FillDLLTypeInfoList(fiCSSPServicesDLL, DLLTypeInfoCSSPServicesList))
            {
                ErrorEvent(new ErrorEventArgs("Could not read the file [" + fiCSSPServicesDLL.FullName + "]"));
                return;
            }
            StatusPermanentEvent(new StatusEventArgs("Loaded [" + fiCSSPServicesDLL.FullName + "] ..."));

            #region Top part Enums.cs
            sb.AppendLine(@"/*");
            sb.AppendLine(@" * Auto generated from the CSSPEnumsGenerateCode.proj by clicking on the [Generate EnumsWithHelp.cs] button");
            sb.AppendLine(@" * ");
            sb.AppendLine(@" * Do not edit this file.");
            sb.AppendLine(@" * ");
            sb.AppendLine(@" * Last generated by Charles LeBlanc. ");
            sb.AppendLine(@" * ");
            sb.AppendLine(@" * In order to change this file you should change Enums.cs manually and Include it in the project.");
            sb.AppendLine(@" * You will also need to Exclude this file before recompiling.");
            sb.AppendLine(@" * Once compiled with changes, you will have to run the CSSPEnumsGenerateCode.proj (F5) ");
            sb.AppendLine(@" * and click on the 'Generate EnumsWithHelp.cs' button to regenerate this file.");
            sb.AppendLine(@" * You can then re-include this file to the project while excluding Enums.cs");
            sb.AppendLine(@" * ");
            sb.AppendLine(@" */");
            sb.AppendLine(@"using System;");
            sb.AppendLine(@"using System.Collections.Generic;");
            sb.AppendLine(@"using System.Linq;");
            sb.AppendLine(@"using System.Text;");
            sb.AppendLine(@"using System.Threading.Tasks;");
            sb.AppendLine(@"using System.Globalization;");
            sb.AppendLine(@"using System.Threading;");
            sb.AppendLine(@"using System.Net;");
            sb.AppendLine(@"");
            sb.AppendLine(@"namespace CSSPEnums");
            sb.AppendLine(@"{");
            sb.AppendLine(@"    /// <summary>");
            sb.AppendLine(@"    /// > [!NOTE]");
            sb.AppendLine(@"    /// > <para>Class holding all Enum used in CSSP applications and methods used to get text associated with the Enum in both languages [en, fr]</para>");
            sb.AppendLine(@"    /// > <para>**Used by** : [CSSPModels](CSSPModels.html), [CSSPServices](CSSPServices.html)</para>");
            sb.AppendLine(@"    /// > <para>**Return to [CSSPEnums](CSSPEnums.html)**</para>");
            sb.AppendLine(@"    /// </summary>");
            sb.AppendLine(@"    public partial class Enums");
            sb.AppendLine(@"    {");
            sb.AppendLine(@"        #region Variables");
            sb.AppendLine(@"        #endregion Variables");
            sb.AppendLine(@"");
            sb.AppendLine(@"        #region Properties");
            sb.AppendLine(@"        /// <summary>");
            sb.AppendLine(@"        /// > [!NOTE]");
            sb.AppendLine(@"        /// > <para>**Language requested for accessing text representing the enumeration**</para>");
            sb.AppendLine(@"        /// > <para>**Allowable values are [en, fr]**</para>");
            sb.AppendLine(@"        /// </summary>");
            sb.AppendLine(@"        /// <param name=""Lang"">The language to use when getting the text of the enumerations</param>");
            sb.AppendLine(@"        public string Lang { get; set; }");
            sb.AppendLine(@"        #endregion Properties");
            sb.AppendLine(@"");
            sb.AppendLine(@"        #region Constructors");
            sb.AppendLine(@"        /// <summary>");
            sb.AppendLine(@"        /// > [!NOTE]");
            sb.AppendLine(@"        /// > <para>**When using en**</para>");
            sb.AppendLine(@"        /// > <code>");
            sb.AppendLine(@"        /// >   <para> CurrentCulture = new CultureInfo(""en-CA"");</para>");
            sb.AppendLine(@"        /// >   <para> CurrentUICulture = new CultureInfo(""en-CA"");</para>");
            sb.AppendLine(@"        /// > </code>");
            sb.AppendLine(@"        /// > <para>**When using fr**</para>");
            sb.AppendLine(@"        /// > <code>");
            sb.AppendLine(@"        /// >   <para> CurrentCulture = new CultureInfo(""fr-CA"");</para>");
            sb.AppendLine(@"        /// >   <para> CurrentUICulture = new CultureInfo(""fr-CA"");</para>");
            sb.AppendLine(@"        /// > </code>");
            sb.AppendLine(@"        /// </summary>");
            sb.AppendLine(@"        /// <param name=""Lang"">The language to use when getting the text of the enumerations</param>");
            sb.AppendLine(@"        /// <example>");
            sb.AppendLine(@"        ///     <code>");
            sb.AppendLine(@"        ///         Enums enums = new Enums(""en"")");
            sb.AppendLine(@"        ///     </code>");
            sb.AppendLine(@"        ///     or");
            sb.AppendLine(@"        ///     <code>");
            sb.AppendLine(@"        ///         Enums enums = new Enums(""fr"")</c>");
            sb.AppendLine(@"        ///     </code>");
            sb.AppendLine(@"        /// </example>");
            sb.AppendLine(@"        public Enums(string Lang)");
            sb.AppendLine(@"        {");
            sb.AppendLine(@"            this.Lang = Lang;");
            sb.AppendLine(@"            if (this.Lang == ""fr"")");
            sb.AppendLine(@"            {");
            sb.AppendLine(@"                Thread.CurrentThread.CurrentCulture = new CultureInfo(""fr-CA"");");
            sb.AppendLine(@"                Thread.CurrentThread.CurrentUICulture = new CultureInfo(""fr-CA"");");
            sb.AppendLine(@"            }");
            sb.AppendLine(@"            else");
            sb.AppendLine(@"            {");
            sb.AppendLine(@"                Thread.CurrentThread.CurrentCulture = new CultureInfo(""en-CA"");");
            sb.AppendLine(@"                Thread.CurrentThread.CurrentUICulture = new CultureInfo(""en-CA"");");
            sb.AppendLine(@"            }");
            sb.AppendLine(@"        }");
            sb.AppendLine(@"        #endregion Construtors");
            sb.AppendLine(@"");
            sb.AppendLine(@"    }");
            #endregion Top part Enums.cs

            #region Top part PolSourceObsInfoEnumGenerated.cs
            sbPol.AppendLine(@"/*");
            sbPol.AppendLine(@" * Auto generated from the CSSPEnumsGenerateCode.proj by clicking on the [Generate all code files] button");
            sbPol.AppendLine(@" * ");
            sbPol.AppendLine(@" * Do not edit this file.");
            sbPol.AppendLine(@" * ");
            sbPol.AppendLine(@" * Last generated by Charles LeBlanc. ");
            sbPol.AppendLine(@" * ");
            sbPol.AppendLine(@" * In order to change this file you will need to change ");
            sbPol.AppendLine(@" * the 'Pol Source Grouping.xlsm' which is potentially located on the desktop.");
            sbPol.AppendLine(@" * You then need to regenerate the 'PolSourceObsInfoEnumGenerated.cs' file ");
            sbPol.AppendLine(@" * using the 'PolSourceGroupingGenerateCode.proj'");
            sbPol.AppendLine(@" * You then need to include the 'PolSourceObsInfoEnumGenerated.cs' file in the project ");
            sbPol.AppendLine(@" * while exluding the 'PolSourceObsInfoEnumGeneratedWithHelp.cs' and recompile");
            sbPol.AppendLine(@" * Once compiled with changes, you will have to run the CSSPEnumsGenerateCode.proj (F5) ");
            sbPol.AppendLine(@" * and click on the 'Generate EnumsWithHelp.cs' button to regenerate this file.");
            sbPol.AppendLine(@" * You can then re-include this file to the project while excluding PolSourceObsInfoEnumGenerated.cs");
            sbPol.AppendLine(@" * ");
            sbPol.AppendLine(@" */");
            sbPol.AppendLine(@"using System;");
            sbPol.AppendLine(@"using System.Collections.Generic;");
            sbPol.AppendLine(@"using System.Linq;");
            sbPol.AppendLine(@"using System.Text;");
            sbPol.AppendLine(@"using System.Threading.Tasks;");
            sbPol.AppendLine(@"");
            sbPol.AppendLine(@"namespace CSSPEnums");
            sbPol.AppendLine(@"{");
            #endregion Top part PolSourceObsInfoEnumGenerated.cs

            int EnumsCount = 0;
            foreach (DLLTypeInfo dllTypeInfoEnums in DLLTypeInfoCSSPEnumsList)
            {
                StringBuilder sbType = new StringBuilder();

                //StatusTempEvent(new StatusEventArgs("Doing [" + dllTypeInfoEnums.Name + "]"));

                if (dllTypeInfoEnums.IsEnum)
                {
                    StringBuilder sbModels = new StringBuilder();
                    StringBuilder sbServices = new StringBuilder();

                    foreach (DLLTypeInfo dllTypeInfoModels in DLLTypeInfoCSSPModelsList)
                    {
                        EnumsCount += 1;
                        if (EnumsCount % 100 == 0)
                        {
                            StatusTempEvent(new StatusEventArgs("Doing [" + dllTypeInfoEnums.Name + "] [" + dllTypeInfoModels.Name + "]"));
                        }
                        foreach (DLLPropertyInfo dllPropertyInfo in dllTypeInfoModels.PropertyInfoList)
                        {
                            if (dllPropertyInfo.CSSPProp.PropType == dllTypeInfoEnums.Type.Name)
                            {
                                string TypeNameModels = dllTypeInfoModels.Name;
                                sbModels.Append(@"[" + dllTypeInfoModels.Name + "] (CSSPModels." + dllTypeInfoModels.Name + @".html#CSSPModels_" + dllTypeInfoModels.Name + "_" + dllPropertyInfo.CSSPProp.PropName + "), ");
                                sbServices.Append(@"[" + dllTypeInfoModels.Name + "Service" + "] (CSSPServices." + dllTypeInfoModels.Name + @"Service.html), ");
                            }
                        }
                    }


                    sbType.AppendLine(@"    /// <summary>");
                    sbType.AppendLine(@"    /// > [!NOTE]");
                    sbType.AppendLine(@"    /// > ");
                    if (sbModels.ToString().Length > 0)
                    {
                        sbModels = sbModels.Remove(sbModels.Length - 2, 2);
                        sbServices = sbServices.Remove(sbServices.Length - 2, 2);
                        sbType.AppendLine(@"    /// > <para>**Used by [CSSPModels](CSSPModels.html)** : " + sbModels.ToString() + "</para>");
                        sbType.AppendLine(@"    /// > <para>**Used by [CSSPServices](CSSPServices.html)** : " + sbServices.ToString() + "</para>");
                    }

                    sbType.AppendLine(@"    /// > <para>**Return to [CSSPEnums](CSSPEnums.html)**</para>");
                    sbType.AppendLine(@"    /// </summary>");
                    sbType.AppendLine(@"    /// <remarks>");
                    sbType.AppendLine(@"    /// <code>");
                    sbType.AppendLine(@"    ///     public enum " + dllTypeInfoEnums.Type.Name + "");
                    sbType.AppendLine(@"    ///     {");
                    foreach (DLLFieldInfo dllFieldInfo in dllTypeInfoEnums.FieldInfoList)
                    {
                        if (dllTypeInfoEnums.IsEnum)
                        {
                            string fName = dllFieldInfo.Name;
                            sbType.AppendLine(@"    ///         " + fName + " = " + ((int)dllFieldInfo.FieldInfo.GetValue(fName)).ToString() + ",");
                        }
                    }
                    sbType.AppendLine(@"    ///     }");
                    sbType.AppendLine(@"    /// </code>");

                    sbType.AppendLine(@"    /// </remarks>");
                    sbType.AppendLine(@"    public enum " + dllTypeInfoEnums.Type.Name);
                    sbType.AppendLine(@"    {");
                    foreach (DLLFieldInfo dllFieldInfo in dllTypeInfoEnums.FieldInfoList)
                    {
                        if (dllTypeInfoEnums.IsEnum)
                        {
                            string fName = dllFieldInfo.Name;
                            int IntVal = (int)dllFieldInfo.FieldInfo.GetValue(dllFieldInfo.Name);

                            sbType.AppendLine(@"        /// <summary>");
                            sbType.AppendLine(@"        /// " + IntVal.ToString() + " -- en [" + enumsEn.GetResValueForTypeAndID(dllTypeInfoEnums.Type, IntVal) + "] ---- fr [" + enumsFr.GetResValueForTypeAndID(dllTypeInfoEnums.Type, IntVal) + "]");
                            sbType.AppendLine(@"        /// </summary>");
                            sbType.AppendLine(@"        " + fName + " = " + IntVal.ToString() + ",");
                        }
                    }
                    sbType.AppendLine(@"    }");
                }

                if (dllTypeInfoEnums.Name == "PolSourceObsInfoEnum")
                {
                    sbPol.Append(sbType);
                    sbPol.AppendLine(@"}");
                }
                else
                {
                    sb.Append(sbType);
                }

            }
            sb.AppendLine(@"");
            sb.AppendLine(@"    /// <summary>");
            sb.AppendLine(@"    /// > [!NOTE]");
            sb.AppendLine(@"    /// > Class representing the Enumeration ID and Text in allowable languages LanguageEnum.en, LanguageEnum.fr");
            sb.AppendLine(@"    /// </summary>");
            sb.AppendLine(@"    public class EnumIDAndText");
            sb.AppendLine(@"    {");
            sb.AppendLine(@"        /// <summary>");
            sb.AppendLine(@"        /// Enumeration ID");
            sb.AppendLine(@"        /// </summary>");
            sb.AppendLine(@"        /// <param name=""EnumID"">The ID of the Enumeration</param>");
            sb.AppendLine(@"        public int EnumID { get; set; }");
            sb.AppendLine(@"        /// <summary>");
            sb.AppendLine(@"        /// Enumeration Text in allowable languages [en, fr]");
            sb.AppendLine(@"        /// </summary>");
            sb.AppendLine(@"        /// <param name=""EnumText"">The text associated with the Enumeration ID</param>");
            sb.AppendLine(@"        public string EnumText { get; set; }");
            sb.AppendLine(@"    }");
            sb.AppendLine(@"");
            sb.AppendLine(@"}");

            using (StreamWriter sw = fi.CreateText())
            {
                sw.Write(sb.ToString());
            }
            StatusTempEvent(new StatusEventArgs("Created [" + fi.FullName + "] ..."));
            StatusPermanentEvent(new StatusEventArgs("Created [" + fi.FullName + "] ..."));

            using (StreamWriter sw = fiPol.CreateText())
            {
                sw.Write(sbPol.ToString());
            }
            StatusTempEvent(new StatusEventArgs("Created [" + fiPol.FullName + "] ..."));
            StatusPermanentEvent(new StatusEventArgs("Created [" + fiPol.FullName + "] ..."));
        }
    }
}
